name : gradle.build

on :
  push :
  pull_request :
  workflow_dispatch :

jobs :
  build :
    runs-on : ubuntu-latest
    env:
      BUILD: ${{ github.run_number }}
      SHA: ${{ github.sha }}
      WEBHOOK: ${{ secrets.Discord }}

    steps :
      - name : Check out repository
        uses : actions/checkout@v2

      - name : Check out submodules
        uses : snickerbockers/submodules-init@v4

      - name : Set up JDK
        uses : actions/setup-java@v1
        with :
          java-version : 1.8

      - name : Gradle cache
        uses : actions/cache@v2
        with :
          path : |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key : ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys : |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew      
      - name : Build forge mod
        run : ./gradlew --build-cache build

      - name: Rename built forge mod
        run: mv build/libs/Ananta-*.jar Ananta-${{ github.run_number }}.jar

      - name : Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs/Ananta-*.jar

      - name : Send Discord build message
        if: github.ref == 'refs/heads/master'
        run : |
          COMMITMESSAGE=`git log --pretty=format:'- \`%h\` %s' -5 --reverse` &&
          (curl "$WEBHOOK" -sS -H "Content-Type:application/json" -X POST -d "{\"content\":null,\"embeds\":[{\"title\":\"Build $BUILD\",\"description\":\"**Branch:** $BRANCH_NAME\\n**Changes:**\\n$COMMITMESSAGE\",\"url\":\"https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\",\"color\":1487872,\"fields\":[{\"name\":\"Artifacts:\",\"value\":\"- [Ananta-$BUILD.zip](https://nightly.link/RitomG69/Ananta/workflows/gradle/master/Package.zip)\"}],\"footer\":{\"text\":\"$GITHUB_REPOSITORY\"},\"thumbnail\":{\"url\":\"https://raw.githubusercontent.com/lambda-client/lambda/master/src/main/resources/assets/minecraft/lambda/lambda_map.png\"}}],\"username\":\"Github Actions\",\"avatar_url\":\"https://www.2b2t.com.au/assets/github.jpeg\"}")
